version: '3.7'

services:
  awesomeproject:
    depends_on:
      - postgres
      - redis
      - nats
      - clickhouse
    build:
      context: .
    volumes:
      - ./config/:/bin/app/config/
    links:
      - "postgres:postgres"
      - "redis:redis"
      - "clickhouse:clickhouse"
      - "nats:nats"
    environment:
      CONFIG_PATH: "./config/config.yaml"
      REDIS_ADD: "redis"
      CH_ADDR: "clickhouse"
      NATS_URL: "nats"
      POSTGRES_URL: "postgres://artem:qwwerty@postgres/awesomedb?sslmode=disable"



  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "artem"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "awesomedb"
    restart: on-failure
    volumes:
      - ./schema/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass qwerty


  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./schema/clickhouse/:/docker-entrypoint-initdb.d/
    environment:
      CLICKHOUSE_PASSWORD: "qwerty"
      CLICKHOUSE_USER: "artem"
      CLICKHOUSE_DB: "awesomedb"


  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--http_port 8222 -js"
