version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "artem"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "awesomedb"
    restart: on-failure
    volumes:
      - ./schema/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - ${POSTGRES_PORT:-5555}:5432
