env: "local" # dev, prod

storage_paths: "./storage/sso.db"

clickhouse:
  port: "9000"
  host: "localhost"
  database: "database"
  username: "artem"
  password: "qwerty"
  client: "client-test"
  version: "0.1"

postgres:
  port: "5436"
  host: "localhost"
  username: "postgres"
  dbname: "postgres"
  ssl_mode: "disable"
  password: "qwerty"

